name: order
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # flutter_launcher_icons: ^0.11.0
  get: ^4.6.5
  intl: ^0.17.0
  connectivity: ^3.0.2
  dio: ^4.0.6
  awesome_dialog: ^3.0.2
  lottie: ^2.1.0
  dio_http_cache: ^0.3.0
  clay_containers: ^0.3.2
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_flutter: ^1.1.0
  syncfusion_flutter_charts: ^19.1.54

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Black-Italic.ttf
        - asset: assets/fonts/Cera-Pro-Black.ttf
        - asset: assets/fonts/Cera-Pro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cera-Pro-Light.ttf
          weight: 400
        - asset: assets/fonts/Cera-Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cera-Pro-Regular-Italic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
